const filters = {
  "app engine": ["google app engine"],
  appengine: ["google app engine"],
  "html/css": ["html", "css"],
  "html/css/js": ["html", "css", "javascript"],
  js: ["javascript"],
  javajava: ["java"],
  "javascript/html/css": ["html", "css", "javascript"],
  javascipt: ["javascript"],
  "javascript/html5/css3": ["html", "css", "javascript"],
  "java script": ["javascript"],
  "php/javascript/html": ["php", "javascript", "html"],
  "php/javascript/ajax": ["php", "javascript", "ajax"],
  "html/javascript": ["html", "javascript"],
  "c/c++": ["c", "c++"],
  "css/html": ["css", "html"],
  "web/html/css": ["web", "html", "css"],
  react: ["javascript", "frontend", "react"],
  angular: ["javascript", "frontend", "angular"],
  node: ["node.js"],
  nodejs: ["node.js"],
  vue: ["vue.js"],
  vuejs: ["vue.js"],
  "vue.js": ["javascript", "frontend", "vue.js"],
  reactjs: ["javascript", "frontend", "react"],
  "react.js": ["javascript", "frontend", "react"],
  "reactjs javascript": ["react", "javascript"],
  golang: ["go"],
  "python 3": ["python"],
  html5: ["html"],
  "html5/css3": ["html", "css"],
  css3: ["css"],
  machinelearning: ["machine learning"],
  "machine learning (ml)": ["machine learning"],
  "c++11": ["c++"],
  "c++14": ["c++"],
  "c++17": ["c++"],
  "c++20": ["c++"],
  cpp: ["c++"],
  "c\\c++": ["c", "c++"],
  "c/c+": ["c", "c++"],
  "c/rust/go": ["c", "rust", "go"],
  nextjs: ["javascript", "frontend", "next.js", "react"],
  "next.js": ["javascript", "frontend", "next.js", "react"],
  "artificial-intelligence": ["ai"],
  "artificial intelligence": ["ai"],
  "data-science": ["data science"],
  "jupyter notebook": ["jupyter"],
  mern: ["mongodb", "express.js", "react", "node.js"],
  "express.js": ["javascript", "backend", "express.js"],
  "dart/flutter": ["mobile", "dart", "flutter"],
  flutter: ["mobile", "flutter"],
  dart: ["mobile", "dart"],
  android: ["mobile", "android"],
  ios: ["mobile", "ios"],
  "shell script": ["shell"],
  llms: ["llm"],
  "django+postgresql": ["django", "postgresql"],
  postgres: ["postgresql"],
  "git/github": ["git", "github"],
  "react-native": ["react", "mobile", "react native"],
  "react native": ["react", "mobile", "react native"],
  mongo: ["mongodb"],
  deeplearning: ["deep learning"],
  "sql/nosql": ["database"],
  "rest api": ["api", "rest"],
  "restful api": ["api", "rest"],
  rest: ["api", "rest"],
  graphql: ["api", "graphql"],
  grpc: ["api", "grpc"],
  mongodb: ["database", "mongodb"],
  mysql: ["database", "mysql"],
  postgresql: ["database", "postgresql"],
  sqlite: ["database", "sqlite"],
  redis: ["database", "redis"],
  elasticsearch: ["database", "elasticsearch"],
  springboot: ["spring boot"],
  angularjs: ["angular"],
  "c language": ["c"],
  "c programming": ["c"],
  databases: ["database"],
  apis: ["api"],
  reactnative: ["react native"],
  golan: ["go"],
  "gnu/linux": ["linux"],
  "android/ios": ["android", "ios"],
  "tcp/udp": ["tcp", "udp"],
  "x86 assembly": ["x86", "assembly"],
  "apache kafka": ["kafka"],
  "big data science": ["big data", "data science"],
  testing: ["testing"],
  colab: ["colab"],
  oauth: ["oauth"],
  "github actions": ["github actions"],
  chromium: ["chromium"],
  "json schema": ["json schema"],
  blockchain: ["blockchain"],
  llm: ["llm"],
  "web apps": ["web"],
  "web development": ["web"],
  "linux kernel": ["linux", "kernel"],
  "angular.js": ["angular"],
  qt5: ["qt"],
  javascr: ["javascript"],
  javasc: ["javascript"],
  phyton: ["python"],
  pthon: ["python"],
  pyth: ["python"],
  "#js": ["javascript"],
  canvas: ["html5 canvas"],
  "ros/gazebo": ["ros", "gazebo"],
  "python deep learning frameworks": ["python", "deep learning"],
  gcp: ["google cloud"],
  "google cloud platform": ["google cloud"],
  "apache spark": ["spark"],
  "ci/cd": ["ci", "cd"],
  webs: ["web"],
  github: ["git", "github"],
  asyncapi: ["api", "asyncapi"],
  "d3.js": ["d3"],
  "generative ai": ["ai"],
  "r-project": ["r"],
  "#llvm": ["llvm"],
  osx: ["macos"],
  container: ["containers"],
  "linux distribution": ["linux"],
  "c++ libraries c++11 c++14 c++17 c++20": ["c++"],
  "object-oriented": ["object oriented programming"],
  "natural language processing": ["machine learning", "nlp"],
  rails: ["ruby on rails"],
  "apache beam": ["apache beam"],
  "gnu autotools": ["autotools"],
  make: ["gnu make"],
  "c++ template metaprogramming": ["c++"],
  "open source databases": ["database"],
  pytorch: ["machine learning", "deep learning", "pytorch"],
  tensorflow: ["machine learning", "deep learning", "tensorflow"],
  keras: ["machine learning", "deep learning", "keras"],
  jax: ["machine learning", "deep learning", "jax"],
  "scikit-learn": ["machine learning", "scikit-learn"],
  opencv: ["machine learning", "computer vision", "opencv"],
  "computer vision": ["machine learning", "computer vision"],
  huggingface: ["machine learning", "huggingface"],
  "multimodel ai": ["machine learning"],
  nlp: ["machine learning", "nlp"],
  deeplearning: ["machine learning", "deep learning"],
  "deep learning": ["machine learning", "deep learning"],
  ai: ["machine learning", "ai"],
  numpy: ["python", "data science", "numpy"],
  pandas: ["python", "data science", "pandas"],
  scipy: ["python", "data science", "scipy"],
  statistics: ["data science"],
  flask: ["python", "backend", "web", "flask"],
  spring: ["java", "backend", "spring"],
  "spring boot": ["java", "backend", "spring", "spring boot"],
  bootstrap: ["css", "frontend", "bootstrap"],
  jquery: ["javascript", "jquery"],
  nosql: ["database"],
  sql: ["database"],
  rdbms: ["database"],
  databases: ["database"],
  "web services": ["web"],
  "web apps": ["web"],
  "web development": ["web"],
  "embedded systems": ["embedded"],
  "json schema": ["json"],
  "json api": ["json", "api"],
  "kubernetes operators": ["kubernetes"],
  "cloud storage": ["cloud"],
  firebase: ["cloud", "firebase"],
  docker: ["devops", "docker"],
  kubernetes: ["devops", "kubernetes"],
  jenkins: ["devops", "jenkins"],
  ansible: ["devops", "ansible"],
  aws: ["cloud", "aws"],
  opengl: ["graphics", "opengl"],
  vulkan: ["graphics", "vulkan"],
  cuda: ["parallel computing", "cuda"],
  solidity: ["blockchain", "solidity"],
  "html5 canvas": ["html"],
  gobject: ["c"],
  "unreal engine": ["unreal engine"],
  cakephp: ["php", "cakephp"],
  "meteor.js": ["javascript", "meteor.js"],
  scss: ["css", "scss"],
  "technical writing": [],
  "google earth": [],
  workflows: [],
  "many more": [],
  documentation: [],
  verification: [],
  "fault tolerant": [],
  screwdriver: ["devops", "screwdriver"],
  spinnaker: ["devops", "spinnaker"],
  tekton: ["devops", "tekton"],
}

const filter = tech => {
  const lowerTech = tech.toLowerCase().trim()
  if (lowerTech in filters) {
    return filters[lowerTech]
  }

  return [tech.trim()]
}

module.exports = {
  filter: filter,
}
