const filters = {
  ai: ["artificial intelligence"],
  "ai/ml": ["artificial intelligence", "machine learning"],
  "ml/al": ["artificial intelligence", "machine learning"],
  "generative ai": ["artificial intelligence"],
  genai: ["artificial intelligence"],
  "artificial intelligence": ["artificial intelligence"],
  "machine learning": ["machine learning"],
  "machine-learning": ["machine learning"],
  "deep learning": ["deep learning"],
  "deep-learning": ["deep learning"],
  nlp: ["natural language processing"],
  "natural language processing": ["natural language processing"],
  web: ["web"],
  "web development": ["web"],
  "web applications": ["web"],
  "web application": ["web"],
  "web apps": ["web"],
  webapps: ["web"],
  "front-end": ["web"],
  frontend: ["web"],
  backend: ["web"],
  "full stack": ["web"],
  "full stack web and mobile": ["web", "mobile"],
  "data science": ["data"],
  "data-science": ["data"],
  "data analysis": ["data"],
  "data visualization": ["data"],
  "data visualisation": ["data"],
  "data analytics": ["data"],
  "data processing": ["data"],
  "data management": ["data"],
  "data integration": ["data"],
  "data-wrangling": ["data"],
  "data-collection": ["data"],
  databases: ["database"],
  "database systems": ["database"],
  compilers: ["compiler"],
  android: ["mobile"],
  cybersecurity: ["security"],
  "cloud computing": ["cloud"],
  "cloud infrastructure": ["cloud"],
  "embedded systems": ["embedded"],
  "embedded hardware": ["embedded"],
  embeddded: ["embedded"],
  "game development": ["games"],
  "game design": ["games"],
  gaming: ["games"],
  apis: ["api"],
  ui: ["user interface"],
  "end user application": ["applications"],
  "end user applications": ["applications"],
  application: ["applications"],
  apps: ["applications"],
  "application development": ["applications"],
  "app development": ["applications"],
  "mobile apps": ["mobile", "applications"],
  "software analysis": ["software engineering"],
  software: ["software engineering"],
  "free software": ["software engineering"],
  "software development": ["software engineering"],
  llm: ["artificial intelligence"],
  llms: ["artificial intelligence"],
  "health care": ["health"],
  healthcare: ["health"],
  heathcare: ["health"],
  ehealth: ["health"],
  "ai in health": ["artificial intelligence", "health"],
  "science and medicine": ["science", "health"],
  "medical imaging": ["health", "computer vision"],
  "real time": ["real-time"],
  "real-time": ["real-time"],
  realtime: ["real-time"],
  music: ["music"],
  "music engraving": ["music"],
  "music recommendation": ["music"],
  "music information retrieval": ["music"],
  "music xml": ["music"],
  musicxml: ["music"],
  "music notation": ["music"],
  aiml: ["artificial intelligence", "machine learning"],
  "ai testing agent": ["artificial intelligence", "testing"],
  "agentic ai": ["artificial intelligence"],
  agent: ["artificial intelligence"],
  agents: ["artificial intelligence"],
  "agent based models": ["artificial intelligence"],
  "multi-agent system": ["artificial intelligence"],
  "multi-agent systems": ["artificial intelligence"],
  "embodied ai": ["artificial intelligence", "robotics"],
  "artificial inteligence": ["artificial intelligence"],
  "ai,": ["artificial intelligence"],
  "continuous integration": ["devops"],
  "continuous delivery": ["devops"],
  ci: ["devops"],
  "ci/cd": ["devops"],
  "testing/ci": ["devops"],
  container: ["containers"],
  containers: ["containers"],
  "rest apis": ["api"],
  "computer-vision": ["computer vision"],
  vision: ["computer vision"],
  network: ["networking"],
  networks: ["networking"],
  "programming languages and development tools": [
    "programming languages",
    "developer tools",
  ],
  "operating system": ["operating systems"],
  "operating-system": ["operating systems"],
  os: ["operating systems"],
  "operating systems": ["operating systems"],
  "development tools": ["developer tools"],
  "programming tools": ["developer tools"],
  "build tools": ["developer tools"],
  tools: ["developer tools"],
  "developer tools": ["developer tools"],
  "programming language": ["programming languages"],
  programming: ["programming languages"],
  "#programming-languages": ["programming languages"],
  "programming languages": ["programming languages"],
  "web platform and services": ["web"],
  django: ["web", "django"],
  react: ["web", "react"],
  webdev: ["web"],
  "web programming": ["web"],
  "learning management": ["education"],
  "neural networks": ["machine learning"],
  "neural network": ["machine learning"],
  mlearning: ["machine learning"],
  "computational biology": ["biology"],
  "high performance computing": ["high-performance computing"],
  hpc: ["high-performance computing"],
  math: ["mathematics"],
  "cloud native infrastructure": ["cloud"],
  "cloud native": ["cloud"],
  "google cloud": ["cloud"],
  "qa automation": ["testing", "automation"],
  communications: ["communication"],
  "realtime communications": ["communication"],
  "internet of things": ["iot"],
  game: ["games"],
  "game engines": ["games"],
  "web-interface": ["user interface"],
  gui: ["user interface"],
  "ui/ux": ["user interface"],
  "ui design": ["user interface"],
  "ux/ui": ["user interface"],
  "enterprise applications": ["applications"],
  "enterprise application": ["applications"],
  "end-user application": ["applications"],
  mysql: ["database"],
  "embedded/automotive": ["embedded"],
  soc: ["embedded"],
  "system-on-chip": ["embedded"],
  "system on chip": ["embedded"],
  "2d/3d graphics": ["graphics"],
  "data mining": ["data"],
  "data extraction": ["data"],
  vr: ["virtual reality"],
  "virtual reality": ["virtual reality"],
  "virtual-reality": ["virtual reality"],
  bioinformtics: ["bioinformatics"],
  "distributed system": ["distributed systems"],
  "distributed systems": ["distributed systems"],
}

const filter = topic => {
  const lowerTopic = topic.toLowerCase().trim()
  if (lowerTopic in filters) {
    return filters[lowerTopic]
  }

  return [topic.trim()]
}

module.exports = {
  filter: filter,
}
