name: 'Propose Merge Filters'
on: workflow_dispatch
jobs:
  technologies:
    permissions:
      models: read
    runs-on: ubuntu-latest
    steps:
      - name: Make code changes
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Read `.agent/skills/propose-merge-filters/SKILL.md` via github MCP and propose merge filters for technologies.
          enable-github-mcp: true
          token: ${{ secrets.GITHUB_TOKEN }}
          github-mcp-token: ${{ secrets.PERSONAL_PAT }}
      - name: Print Output
        id: output
        run: echo "${{ steps.inference.outputs.response }}"
