name: 'Propose Merge Filters'
on: workflow_dispatch
jobs:
  technologies:
    permissions:
      models: read
    runs-on: ubuntu-latest
    steps:
      - name: Make code changes
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Note that all file references are for repository `nishantwrp/gsoc-organizations` and you can use github MCP to read files. 
            1. Look at files in `api/data` directory. Look at the `technologies` array in each file.
            2. Propose merge filters in `api/filters/technology-filters.js` for technologies.
          enable-github-mcp: true
          token: ${{ secrets.GITHUB_TOKEN }}
          github-mcp-token: ${{ secrets.PERSONAL_PAT }}
      - name: Print Output
        id: output
        run: echo "${{ steps.inference.outputs.response }}"
